#!/usr/bin/php

<?php 
use Roul\Cli\CommandsGatherer;

require_once __DIR__ . "/vendor/autoload.php";

$commands = include("Commands.php");

foreach ($commands as $name => $command) {
    new $command;
}
   

CommandsGatherer::run();